name: dartingabout
description: A web app that
version: 0.0.1
#homepage: https://www.example.com
#author: faddat <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: any
  angular2_components:  any
  dartsteem: any
  json_mapper: any
  dquery: any
  polymer: any
  web_components: any


dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- polymer:
    entry_points:
      - web/index.html
